### ISSUE TITLE
I found to be unable to support jsx grammar cause, but do not know how to solve

### ISSUE THREAD

**Issue by wangzhe1995** [babel/babel-jest#49]
`src/app.js`
```javascript
import React, { Component, PropTypes } from 'react';
import ReactDOM, { findDOMNode } from 'react-dom';

class CheckBox extends Component {
  render() {
    return (
      <div></div>
    );
  }
}

export default CheckBox;
```

`__test__/app-test.js`

```javascript
jest.dontMock('../src/app');

import TestUtils from 'react-addons-test-utils';

describe("CheckBox component", function () {
  it("just test", function () {
    let CheckBox = require('../src/app');
    let checkBoxComponent = TestUtils.renderIntoDocument(<CheckBox/>);
  });
});
```

`package.json`

```javascript
{
  "name": "wz-jest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-jest": "^6.0.1",
    "jest-cli": "^0.7.1",
    "react": "^0.14.2",
    "react-addons-test-utils": "^0.14.2",
    "react-dom": "^0.14.2"
  },
  "jest": {
    "rootDir": "./",
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "testFileExtensions": ["es6", "js"],
    "moduleFileExtensions": ["js", "json", "es6"]
  }
}
```

`SyntaxError: /Users/wangzhe/Development/labx/jest/__tests__/app-test.js: Unexpected token (8:57)`
The corresponding code is:
```javascript
let checkBoxComponent = TestUtils.renderIntoDocument(<CheckBox/>);
```

**Comment by sajinshrestha** [comment]
+1. 
`jest-cli@0.7.1` works with `babel-jest@5.2.1`. Not sure how to pass `"presets": ["es2015", "react"]` with `babel-core@6.0.0`. I've tried creating `.babelrc` with following option but no dice.
```
{
  "presets": ["es2015", "react"]
}
```

**Comment by wangzhe1995** [comment]
@sajinshrestha +1

I also tried to add `.babelrc`, but does not work

**Comment by cpojer** [comment]
@sebmck mentioned to me that this should work with a correct .babelrc. Hmmmm.

**Comment by ivantsov** [comment]
@cpojer but what if I don't use .babelrc? Is there another way to configure babel-jest?

**Comment by cpojer** [comment]
I don't think there is any other way, actually. So far I've always had to create my own preprocessor. We are tracking to update the for it documentation here: https://github.com/facebook/jest/pull/605#issuecomment-155855218

Sorry, babel6 came out just a short time ago and we haven't had time to update everything around jest yet :)

**Comment by danielstern** [comment]
I had the same problem. Turns out, I was missing a `.babelrc` file

**Comment by ivantsov** [comment]
Finally I fixed it. First of all, I added .babelrc in the root dir (I run tests via `npm test` from the root, so it's important). 
My .babelrc looks like this:
```
{
  "presets": [
     "react",
     "es2015"
  ]
}
```
Jest config looks as following:
```
"jest": {
  "testRunner": "<rootDir>/node_modules/jest-cli/src/testRunners/jasmine/jasmine2",
  "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
  "unmockedModulePathPatterns": [
    "<rootDir>/node_modules/react",
    "<rootDir>/node_modules/react-dom",
    "<rootDir>/node_modules/react-addons-test-utils",
    "<rootDir>/node_modules/fbjs"
  ],
  "modulePathIgnorePatterns": [
    "<rootDir>/node_modules/"
  ]
} 
```
Be aware, I use jasmine **2** as a runner and it could be another cause why I finally managed to run Jest.

**Comment by wangzhe1995** [comment]
I think you said it right. If you simply join .babelrc file, but because all the default mock for jest, then react is not working correctly, and I was late to try

**Comment by wangzhe1995** [comment]
@ivantsov thx！It work. But must use module.exports replace export default(ES6)，Do you know about?

**Comment by ivantsov** [comment]
@wangzhe1995 oh sorry, my bad. I forgot to say that I use CJS modules but not ES6... Glad to hear you made it work!

**Comment by afc163** [comment]
@ivantsov :+1: jasmine2 works!

**Comment by JorgenG** [comment]
@ivantsov Does this mean that ES6 exports does not work? If that is so, shouldn't that work? Why would we not want to use ES6 exports over CJS exports? I have been struggling for a day to get this new version working, not sure how much more time I can use. (Coming from pre babel 6 and babel-jest 0.5.3)

**Comment by cpojer** [comment]
We are still working on a solution for ES2015 imports on one side and require's on the other. I'm hoping to enable the use of ES2015 imports within tests, finally.

**Comment by avk** [comment]
Found my way here because [the current Jest React tutorial](https://facebook.github.io/jest/docs/tutorial-react.html#setup) doesn't work unless I specify an older version of babel-jest:
`"babel-jest": "^5.3.0",`

**Comment by ivantsov** [comment]
@avk did you try this configuration - https://github.com/babel/babel-jest/issues/49#issuecomment-157985401?

**Comment by bartonhammond** [comment]
@ivantsov My configuration for RN 0.17 is similar except for the Jasmine.  

My non-JSX tests are fine.  The JSX tests fail [https://github.com/facebook/jest/issues/629#issuecomment-166629392](https://github.com/facebook/jest/issues/629#issuecomment-166629392) 

What steps did you perform for ```jasmine2```?  I'll give it a try but not sure the steps.

**Comment by ivantsov** [comment]
@barton

**Comment by bartonhammond** [comment]
@ivantsov - ok - thanks - my .babelrc is same, plus more.

**Comment by crantila** [comment]
I was having similar problems as people in this thread (Babel wasn't running properly). For me it was ```SyntaxError: Unexpected token ...```, which is the ES6 spread operator that Babel should have been compiling but wasn't. Furthermore, Babel clearly *was* running for some of my test modules, but not all of them.

I fixed the problem by adding ```"modulePathIgnorePatterns": ["<rootDir>/node_modules/"]``` to the "jest" part of my `package.json` file, as I saw in [another post in this issue](https://github.com/babel/babel-jest/issues/49#issuecomment-157985401). Of course, in the grand NPM tradition, I have no idea why this works.

---------------------

Also, there appear to be people looking for an alternative to the `.babelrc` files. You can configure Babel (including `babel-jest`, `babelify`, and `babel-cli` all at once) with the "babel" member in `package.json`. Here's an excerpt of my `package.json`:
```json
    "babel": {
        "presets": ["es2015", "react"]
    }
}
```
I prefer this to a `.babelrc` file because all the configuration is consolidated in `package.json`.

**Comment by bartonhammond** [comment]
@crantila Tried your solution but alas, still, my Jest JSX Tests are still failing.

I do have 58 non-JSX tests that pass - see [https://github.com/bartonhammond/snowflake](https://github.com/bartonhammond/snowflake) and run 

```npm test src/reducers```

output:
```
58 tests passed (58 total in 4 test suites, run time 2.06s)
```

My ```.babelrc``` is  sync'd to the react-packager

```
{
  "extends": "react-native/packager/react-packager/.babelrc"  
}
```

Still no LOVE for JSX Jest

**Comment by crantila** [comment]
@bartonhammond I finally managed to get a useful JSX-based test on a public project. Links to the [project](https://github.com/CANTUS-Project/vitrail/tree/713c3ec3fe405de706ef276a992c3d2a5311da1d), the [component under test](https://github.com/CANTUS-Project/vitrail/blob/713c3ec3fe405de706ef276a992c3d2a5311da1d/js/react/itemview.js#L854), and the [test itself](https://github.com/CANTUS-Project/vitrail/blob/713c3ec3fe405de706ef276a992c3d2a5311da1d/vitrail_tests/test_itemview.js#L36).

I don't claim this project demonstrates best practices, and the test shown there is basically trivial. (Also I broke the build in that commit...) However, unlike the bizarre mix of condescension and assuming-you-know seen in most JavaScript documentation, this project is a complete react/babel/babel-jest/jest-cli assembly with working JSX tests.

**Comment by bartonhammond** [comment]
@crantila gee, I hope I'm not using a

> bizarre mix of condescension and assuming-you-know

documentation?

I'm not sure I understand how this will translate for me wrt RN 0.17 as I use a different TestUtil ```const utils = require('react-addons-test-utils'); ``` as used [here](https://github.com/bartonhammond/snowflake/blob/master/src/components/__tests__/FormButton-test.js#L53)  

After I free up from my current commitment, I'll have to dig through this.  I **appreciate** you bringing it to my attention.

**Comment by crantila** [comment]
@bartonhammond I'm sorry if it wasn't clear, but I didn't mean to refer to any project in particular&mdash;certainly not yours, since I have no experience with your work. It's more of a general frustration. When I can't figure out how to make something work, the documentation is either doing something like explaining the virtues of basic unit testing (don't you think I would know this, if I've made it to the depths of a testing framework's API?), or worse, something like telling me about all sorts of functions and what they do, without explaining what the arguments and return values are, or how to import these functions to my program. But anyway!

About importing TestUtils, because the following two lines should be equivalent, I expect it will be straightforward to compare our projects. In fact, this substitution works in [the test file I mentioned above](https://github.com/CANTUS-Project/vitrail/blob/713c3ec3fe405de706ef276a992c3d2a5311da1d/vitrail_tests/test_itemview.js#L36).
```javascript
import TestUtils from 'react-addons-test-utils';
// ... is equivalent to...
const TestUtils = require('react-addons-test-utils');
```

Where you have to watch out is `import` statements with braces. The following two lines should also be equivalent to each other. Even though the `import` version looks similar to the one above, you can see it's not the same at all.
```javascript
import {TestUtils} from 'react-addons-test-utils';
// ... is equivalent to...
const TestUtils = require('react-addons-test-utils').TestUtils;
```
In fact, because `react-addons-test-utils` has no "TestUtils" member, these lines will set `TestUtils` to `undefined`.

Hopefully this will help someone save time with their own import statements!

**Comment by bartonhammond** [comment]
Thanks for clarification. ... I will get back to this in couple of days..

**Comment by bartonhammond** [comment]
I made all the changes suggested here and still the JSX Jest tests fail.  The unexpected token ```{``` is from the test class not being Babel'ized.

```
[SyntaxError: Unexpected token {]
 FAIL  src/components/__tests__/FormButton-test.js 
```

**Comment by jasongonzales23** [comment]
Pretty sure I've tried all the things in this comment thread, and after all the pain of getting babel6 up and running I'd really hate to downgrade, but sadly every single jsx component I am trying to test currently fails with the dreaded: "Error: Failed to get mock metadata:"

Let me know what would be most helpful to share to workaround or solve this.

This is such a major bummer that Jest seems so neglected. It's otherwise really handy.

**Comment by cpojer** [comment]
This is all stuff that people at FB don't run into so it is not a major focus for me right now. Feel free to join the #jest community on discord: facebook.github.io/jest/support.html if you'd like to help out. Once I'm done with https://github.com/facebook/jest/pull/599 I'll fully focus on some of the open source issues that people are having with Jest but I can't really give you a predictable schedule. I'm hoping to be done with that major rewrite in that PR in the next two weeks or so.

**Comment by nhz-io** [comment]
Look here (scroll down):
https://github.com/Ticketmaster/jest-webpack-alias/issues/5

and then look here:
https://github.com/Ticketmaster/jest-webpack-alias

IMHO, babel-jest should adopt the package.json babel entry

**Comment by marco-amoroso** [comment]
I'm also upgrading to Babel6 (due to React Native) and I'm still having the same issues when using `export default` in the files I want to test.

But adding `.default` at the end when requiring the components or files, jest tests are passing now. Thanks @nhz-io

**Comment by steinbachr** [comment]
I ended up having to `npm install babel-preset-es2015` and `npm install babel-preset-react` and also had to create .babelrc with `{"presets": ["es2015", "react"]}`in it

**Comment by rjbernaldo** [comment]
Solution by @steinbachr worked for me! Thanks a lot.

**Comment by cpojer** [comment]
This should be resolved with `jest-cli@next`, https://github.com/facebook/jest/pull/741 and a proper `.babelrc`. I will make sure to improve the documentation for the final 0.9.0 release of Jest :)

**Comment by lebeier** [comment]
Has this issue been solved? I have just installed jest to do unit testing for my react app. I have tried the solutions here and none of them works. And all my js files are written in ES6 syntax.

**Comment by bartonhammond** [comment]
You can check out my working project Snowflake
https://github.com/bartonhammond/snowflake The Jest test run fine including
JSX

**Comment by lebeier** [comment]
@bartonhammond , ok i guess import works in the test files. However, I am getting Runtime Error **SyntaxError: unexpected token ...**

**Comment by cpojer** [comment]
Jest 0.9.0 is going to be released very soon and it'll allow the use of import together with babel; and have babel integration by default.
